version: '3.1'

services:
  app:
    image: python:3
    working_dir: ${PYTHON_WORKDIR_CONTAINER}
    container_name: ${CONTAINER_NAME}
    environment:
      - DEBUG=1
      - CONTAINER_NAME=${CONTAINER_NAME}
      - PYTHON_INSTALL_DJANGO=${PYTHON_INSTALL_DJANGO}
    volumes:
      - ${ROOT_PATH}${PYTHON_PROJECT_PATH}:${PYTHON_WORKDIR_CONTAINER}
      - ${ROOT_PATH}${PYTHON_VENV_PATH}:${PYTHON_VENV_CONTAINER}
      - ${ROOT_PATH}${PYTHON_ENTRYPOINT}:/entrypoint
    ports:
      - ${PYTHON_WEB_PORT}:80
    entrypoint: ["bash","/entrypoint/docker-entrypoint.sh"]
    depends_on:
      - db

  db:
    image: mysql:5
    container_name: ${CONTAINER_NAME}_db
    command: --default-authentication-plugin=mysql_native_password
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
    volumes:
      - ${ROOT_PATH}${MYSQL_VOLUME_MIGRATIONS}:/docker-entrypoint-initdb.d
      - ${ROOT_PATH}${MYSQL_VOLUME_CONF}:/etc/mysql/conf.d
      - ${ROOT_PATH}${MYSQL_VOLUME_DATA}:/var/lib/mysql
      # - ${ROOT_PATH}${MYSQL_VOLUME_LOGS}:/var/log/mysql
      - ${ROOT_PATH}${MYSQL_VOLUME_BACKUPS}:/backups

  adminer:
    image: adminer
    container_name: ${CONTAINER_NAME}_adminer
    restart: 'no'
    ports:
      - ${ADMINER_PORT_GESTOR}:8080
